### ISSUE TITLE
Histogram extraction fails

### ISSUE THREAD

**Issue by dy** [tobius/imagecolors#5]
Hello!
I do a simple static-generator, and I would like to parse dominant image colors. I do

``` js
//imagePath is absolute url to jpg, like `/users/df/projects/site/content/images/1.jpg`
imagecolors.extract(imagePath, 2, function (err, colors) {
    if (err) console.log(err);
});
```

and I get

```
Histogram extraction failed
```

**Comment by dfcreative** [comment]
Windows 7 machine, graphicmagic is 1.3.21 ftp://ftp.graphicsmagick.org/pub/GraphicsMagick/windows/GraphicsMagick-1.3.21-Q16-win64-dll.exe

**Comment by Zugwalt** [comment]
Also seeing this on Windows 10 graphicmagick 1.3.21-q16 64bit.

**Comment by mmisiarek** [comment]
I got it on Mac OS as well

**Comment by RGBz** [comment]
It looks like this uses [imagemagick](http://www.imagemagick.org/script/index.php) as well so that would need to be installed as well on your OS. I was getting this error until I installed imagemagick and now it works fine.

**Comment by tobius** [comment]
These all appear to be issues related to imagemagick not being installed.

**Comment by LeanSaucecode** [comment]
Hi I am having this error even tho I have imagemagick installed.. What can I provide to help you debug this?

Version: ImageMagick 7.0.10-33 Q16 x64 2020-10-04 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 192729111
Features: Cipher DPC HDRI Modules OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg lcms lqr lzma openexr pangocairo png ps raw rsvg tiff webp xml zlib

C:\Users\>node -v
v12.13.0

and I installed graphicmagick
GraphicsMagick 1.3.34 2019-12-24 Q16 http://www.GraphicsMagick.org/
Copyright (C) 2002-2019 GraphicsMagick Group.
Additional copyrights and licenses apply to this software.
See http://www.GraphicsMagick.org/www/Copyright.html for details.

Feature Support:
  Native Thread Safe       yes
  Large Files (> 32 bit)   yes
  Large Memory (> 32 bit)  yes
  BZIP                     yes
  DPS                      no
  FlashPix                 no
  FreeType                 yes
  Ghostscript (Library)    no
  JBIG                     yes
  JPEG-2000                yes
  JPEG                     yes
  Little CMS               yes
  Loadable Modules         yes
  Solaris mtmalloc         no
  OpenMP                   yes (200203 "2.0")
  PNG                      yes
  TIFF                     yes
  TRIO                     no
  Solaris umem             no
  WebP                     yes
  WMF                      yes
  X11                      no
  XML                      yes
  ZLIB                     yes

Windows Build Parameters:

  MSVC Version:            1500
